
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include <ModemManager.h>
#ifndef __MM_ENUMS_TYPES_H__
#define __MM_ENUMS_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "ModemManager-enums.h" */
GType mm_modem_capability_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_CAPABILITY (mm_modem_capability_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_capability_get_string (MMModemCapability val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_capability_build_string_from_mask (MMModemCapability mask);
#endif
GType mm_modem_lock_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_LOCK (mm_modem_lock_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_lock_get_string (MMModemLock val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_lock_build_string_from_mask (MMModemLock mask);
#endif
GType mm_modem_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_STATE (mm_modem_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_state_get_string (MMModemState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_state_build_string_from_mask (MMModemState mask);
#endif
GType mm_modem_state_failed_reason_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_STATE_FAILED_REASON (mm_modem_state_failed_reason_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_state_failed_reason_get_string (MMModemStateFailedReason val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_state_failed_reason_build_string_from_mask (MMModemStateFailedReason mask);
#endif
GType mm_modem_power_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_POWER_STATE (mm_modem_power_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_power_state_get_string (MMModemPowerState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_power_state_build_string_from_mask (MMModemPowerState mask);
#endif
GType mm_modem_state_change_reason_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_STATE_CHANGE_REASON (mm_modem_state_change_reason_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_state_change_reason_get_string (MMModemStateChangeReason val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_state_change_reason_build_string_from_mask (MMModemStateChangeReason mask);
#endif
GType mm_modem_access_technology_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_ACCESS_TECHNOLOGY (mm_modem_access_technology_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_access_technology_get_string (MMModemAccessTechnology val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_access_technology_build_string_from_mask (MMModemAccessTechnology mask);
#endif
GType mm_modem_mode_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_MODE (mm_modem_mode_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_mode_get_string (MMModemMode val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_mode_build_string_from_mask (MMModemMode mask);
#endif
GType mm_modem_band_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_BAND (mm_modem_band_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_band_get_string (MMModemBand val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_band_build_string_from_mask (MMModemBand mask);
#endif
GType mm_modem_port_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_PORT_TYPE (mm_modem_port_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_port_type_get_string (MMModemPortType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_port_type_build_string_from_mask (MMModemPortType mask);
#endif
GType mm_cell_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_CELL_TYPE (mm_cell_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_cell_type_get_string (MMCellType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_cell_type_build_string_from_mask (MMCellType mask);
#endif
GType mm_sms_pdu_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_PDU_TYPE (mm_sms_pdu_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_pdu_type_get_string (MMSmsPduType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_pdu_type_build_string_from_mask (MMSmsPduType mask);
#endif
GType mm_sms_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_STATE (mm_sms_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_state_get_string (MMSmsState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_state_build_string_from_mask (MMSmsState mask);
#endif
GType mm_sms_delivery_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_DELIVERY_STATE (mm_sms_delivery_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_delivery_state_get_string (MMSmsDeliveryState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_delivery_state_build_string_from_mask (MMSmsDeliveryState mask);
#endif
GType mm_sms_storage_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_STORAGE (mm_sms_storage_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_storage_get_string (MMSmsStorage val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_storage_build_string_from_mask (MMSmsStorage mask);
#endif
GType mm_sms_validity_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_VALIDITY_TYPE (mm_sms_validity_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_validity_type_get_string (MMSmsValidityType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_validity_type_build_string_from_mask (MMSmsValidityType mask);
#endif
GType mm_sms_cdma_teleservice_id_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_CDMA_TELESERVICE_ID (mm_sms_cdma_teleservice_id_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_cdma_teleservice_id_get_string (MMSmsCdmaTeleserviceId val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_cdma_teleservice_id_build_string_from_mask (MMSmsCdmaTeleserviceId mask);
#endif
GType mm_sms_cdma_service_category_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SMS_CDMA_SERVICE_CATEGORY (mm_sms_cdma_service_category_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sms_cdma_service_category_get_string (MMSmsCdmaServiceCategory val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sms_cdma_service_category_build_string_from_mask (MMSmsCdmaServiceCategory mask);
#endif
GType mm_modem_location_source_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_LOCATION_SOURCE (mm_modem_location_source_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_location_source_get_string (MMModemLocationSource val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_location_source_build_string_from_mask (MMModemLocationSource mask);
#endif
GType mm_modem_location_assistance_data_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_LOCATION_ASSISTANCE_DATA_TYPE (mm_modem_location_assistance_data_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_location_assistance_data_type_get_string (MMModemLocationAssistanceDataType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_location_assistance_data_type_build_string_from_mask (MMModemLocationAssistanceDataType mask);
#endif
GType mm_modem_contacts_storage_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_CONTACTS_STORAGE (mm_modem_contacts_storage_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_contacts_storage_get_string (MMModemContactsStorage val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_contacts_storage_build_string_from_mask (MMModemContactsStorage mask);
#endif
GType mm_bearer_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_TYPE (mm_bearer_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_type_get_string (MMBearerType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_type_build_string_from_mask (MMBearerType mask);
#endif
GType mm_bearer_ip_method_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_IP_METHOD (mm_bearer_ip_method_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_ip_method_get_string (MMBearerIpMethod val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_ip_method_build_string_from_mask (MMBearerIpMethod mask);
#endif
GType mm_bearer_ip_family_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_IP_FAMILY (mm_bearer_ip_family_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_ip_family_get_string (MMBearerIpFamily val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_ip_family_build_string_from_mask (MMBearerIpFamily mask);
#endif
GType mm_bearer_allowed_auth_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_ALLOWED_AUTH (mm_bearer_allowed_auth_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_allowed_auth_get_string (MMBearerAllowedAuth val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_allowed_auth_build_string_from_mask (MMBearerAllowedAuth mask);
#endif
GType mm_modem_cdma_registration_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_CDMA_REGISTRATION_STATE (mm_modem_cdma_registration_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_cdma_registration_state_get_string (MMModemCdmaRegistrationState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_cdma_registration_state_build_string_from_mask (MMModemCdmaRegistrationState mask);
#endif
GType mm_modem_cdma_activation_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_CDMA_ACTIVATION_STATE (mm_modem_cdma_activation_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_cdma_activation_state_get_string (MMModemCdmaActivationState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_cdma_activation_state_build_string_from_mask (MMModemCdmaActivationState mask);
#endif
GType mm_modem_cdma_rm_protocol_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_CDMA_RM_PROTOCOL (mm_modem_cdma_rm_protocol_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_cdma_rm_protocol_get_string (MMModemCdmaRmProtocol val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_cdma_rm_protocol_build_string_from_mask (MMModemCdmaRmProtocol mask);
#endif
GType mm_modem_3gpp_registration_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_REGISTRATION_STATE (mm_modem_3gpp_registration_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_registration_state_get_string (MMModem3gppRegistrationState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_registration_state_build_string_from_mask (MMModem3gppRegistrationState mask);
#endif
GType mm_modem_3gpp_facility_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_FACILITY (mm_modem_3gpp_facility_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_facility_get_string (MMModem3gppFacility val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_facility_build_string_from_mask (MMModem3gppFacility mask);
#endif
GType mm_modem_3gpp_network_availability_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_NETWORK_AVAILABILITY (mm_modem_3gpp_network_availability_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_network_availability_get_string (MMModem3gppNetworkAvailability val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_network_availability_build_string_from_mask (MMModem3gppNetworkAvailability mask);
#endif
GType mm_modem_3gpp_subscription_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_SUBSCRIPTION_STATE (mm_modem_3gpp_subscription_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_subscription_state_get_string (MMModem3gppSubscriptionState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_subscription_state_build_string_from_mask (MMModem3gppSubscriptionState mask);
#endif
GType mm_modem_3gpp_ussd_session_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_USSD_SESSION_STATE (mm_modem_3gpp_ussd_session_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_ussd_session_state_get_string (MMModem3gppUssdSessionState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_ussd_session_state_build_string_from_mask (MMModem3gppUssdSessionState mask);
#endif
GType mm_modem_3gpp_eps_ue_mode_operation_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_EPS_UE_MODE_OPERATION (mm_modem_3gpp_eps_ue_mode_operation_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_eps_ue_mode_operation_get_string (MMModem3gppEpsUeModeOperation val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_eps_ue_mode_operation_build_string_from_mask (MMModem3gppEpsUeModeOperation mask);
#endif
GType mm_firmware_image_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_FIRMWARE_IMAGE_TYPE (mm_firmware_image_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_firmware_image_type_get_string (MMFirmwareImageType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_firmware_image_type_build_string_from_mask (MMFirmwareImageType mask);
#endif
GType mm_oma_feature_get_type (void) G_GNUC_CONST;
#define MM_TYPE_OMA_FEATURE (mm_oma_feature_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_oma_feature_get_string (MMOmaFeature val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_oma_feature_build_string_from_mask (MMOmaFeature mask);
#endif
GType mm_oma_session_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_OMA_SESSION_TYPE (mm_oma_session_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_oma_session_type_get_string (MMOmaSessionType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_oma_session_type_build_string_from_mask (MMOmaSessionType mask);
#endif
GType mm_oma_session_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_OMA_SESSION_STATE (mm_oma_session_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_oma_session_state_get_string (MMOmaSessionState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_oma_session_state_build_string_from_mask (MMOmaSessionState mask);
#endif
GType mm_oma_session_state_failed_reason_get_type (void) G_GNUC_CONST;
#define MM_TYPE_OMA_SESSION_STATE_FAILED_REASON (mm_oma_session_state_failed_reason_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_oma_session_state_failed_reason_get_string (MMOmaSessionStateFailedReason val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_oma_session_state_failed_reason_build_string_from_mask (MMOmaSessionStateFailedReason mask);
#endif
GType mm_call_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_CALL_STATE (mm_call_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_call_state_get_string (MMCallState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_call_state_build_string_from_mask (MMCallState mask);
#endif
GType mm_call_state_reason_get_type (void) G_GNUC_CONST;
#define MM_TYPE_CALL_STATE_REASON (mm_call_state_reason_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_call_state_reason_get_string (MMCallStateReason val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_call_state_reason_build_string_from_mask (MMCallStateReason mask);
#endif
GType mm_call_direction_get_type (void) G_GNUC_CONST;
#define MM_TYPE_CALL_DIRECTION (mm_call_direction_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_call_direction_get_string (MMCallDirection val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_call_direction_build_string_from_mask (MMCallDirection mask);
#endif
GType mm_modem_firmware_update_method_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_FIRMWARE_UPDATE_METHOD (mm_modem_firmware_update_method_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_firmware_update_method_get_string (MMModemFirmwareUpdateMethod val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_firmware_update_method_build_string_from_mask (MMModemFirmwareUpdateMethod mask);
#endif
GType mm_bearer_multiplex_support_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_MULTIPLEX_SUPPORT (mm_bearer_multiplex_support_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_multiplex_support_get_string (MMBearerMultiplexSupport val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_multiplex_support_build_string_from_mask (MMBearerMultiplexSupport mask);
#endif
GType mm_bearer_apn_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_APN_TYPE (mm_bearer_apn_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_apn_type_get_string (MMBearerApnType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_apn_type_build_string_from_mask (MMBearerApnType mask);
#endif
GType mm_modem_3gpp_packet_service_state_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_PACKET_SERVICE_STATE (mm_modem_3gpp_packet_service_state_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_packet_service_state_get_string (MMModem3gppPacketServiceState val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_packet_service_state_build_string_from_mask (MMModem3gppPacketServiceState mask);
#endif
GType mm_sim_type_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SIM_TYPE (mm_sim_type_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sim_type_get_string (MMSimType val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sim_type_build_string_from_mask (MMSimType mask);
#endif
GType mm_sim_esim_status_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SIM_ESIM_STATUS (mm_sim_esim_status_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sim_esim_status_get_string (MMSimEsimStatus val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sim_esim_status_build_string_from_mask (MMSimEsimStatus mask);
#endif
GType mm_sim_removability_get_type (void) G_GNUC_CONST;
#define MM_TYPE_SIM_REMOVABILITY (mm_sim_removability_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_sim_removability_get_string (MMSimRemovability val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_sim_removability_build_string_from_mask (MMSimRemovability mask);
#endif
GType mm_modem_3gpp_mico_mode_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_MICO_MODE (mm_modem_3gpp_mico_mode_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_mico_mode_get_string (MMModem3gppMicoMode val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_mico_mode_build_string_from_mask (MMModem3gppMicoMode mask);
#endif
GType mm_modem_3gpp_drx_cycle_get_type (void) G_GNUC_CONST;
#define MM_TYPE_MODEM_3GPP_DRX_CYCLE (mm_modem_3gpp_drx_cycle_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_modem_3gpp_drx_cycle_get_string (MMModem3gppDrxCycle val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_modem_3gpp_drx_cycle_build_string_from_mask (MMModem3gppDrxCycle mask);
#endif
GType mm_bearer_access_type_preference_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_ACCESS_TYPE_PREFERENCE (mm_bearer_access_type_preference_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_access_type_preference_get_string (MMBearerAccessTypePreference val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_access_type_preference_build_string_from_mask (MMBearerAccessTypePreference mask);
#endif
GType mm_bearer_roaming_allowance_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_ROAMING_ALLOWANCE (mm_bearer_roaming_allowance_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_FLAGS__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_roaming_allowance_get_string (MMBearerRoamingAllowance val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_roaming_allowance_build_string_from_mask (MMBearerRoamingAllowance mask);
#endif
GType mm_bearer_profile_source_get_type (void) G_GNUC_CONST;
#define MM_TYPE_BEARER_PROFILE_SOURCE (mm_bearer_profile_source_get_type ())

/* Define type-specific symbols */
#undef __MM_IS_ENUM__
#undef __MM_IS_FLAGS__
#define __MM_IS_ENUM__

#if defined __MM_IS_ENUM__
const gchar *mm_bearer_profile_source_get_string (MMBearerProfileSource val);
#endif

#if defined __MM_IS_FLAGS__
gchar *mm_bearer_profile_source_build_string_from_mask (MMBearerProfileSource mask);
#endif
G_END_DECLS

#endif /* __MM_ENUMS_TYPES_H__ */

/* Generated data ends here */

