/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define FHS_PREFIX ""

/* Build with Capsicum support */
#undef HAVE_CAPSICUM

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

#define HAVE_GMODULE

#undef HAVE_LIBUTF8PROC

/* Build with socks support */
#undef HAVE_SOCKS

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <term.h> header file. */
#define HAVE_TERM_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

#define PACKAGE_TARNAME "irssi"

#define PACKAGE_VERSION "1.4.4"

/* true color support in terminal */
#define TERM_TRUECOLOR

/* use GRegex for regular expressions */
#define USE_GREGEX

/* Enable large inode numbers on Mac OS X 10.5. */
#define _DARWIN_USE_64_BIT_INODE 1

